### ISSUE TITLE
inSubgraphSize and outSubgraphSize : Should node include itself in count?

### ISSUE THREAD

**Issue by jayqi** [UptakeOpenSource/pkgnet#191]
Look at `baseballstats`:

<img width="424" alt="screen shot 2019-02-23 at 5 01 26 pm" src="https://user-images.githubusercontent.com/2721979/53292747-e2b56a80-378c-11e9-815f-0a839f1dfc24.png">

```
           node inSubgraphSize outSubgraphSize
1:          OPS              1               4
2:      at_bats              4               1
3:  batting_avg              2               2
4:  on_base_pct              1               1
5: slugging_avg              2               2
```

We can see that these calculations include each node itself in the count. For example, `on_base_pct` is an orphaned node but it has counts of 1 in both directions.

These measures are included to capture the idea of "number of dependents" and "number of dependencies". I propose to more intuitively and directly represent that idea, we subtract 1 from all of these counts. 

This is a change I'm planning to make in #181.

**Comment by bburns632** [comment]
@jayqi , since those metrics say "Subgraph Size", I would say include the all nodes in the count (including the original one).  Graph size (or order) is conventionally all nodes in the graph, and since we are using that specific term "subgraph", we should follow that convention.  

If those metrics said "number of dependents", "number of dependencies", or "number of neighbors" I would say N -1 would be appropriate.

 [](http://mathworld.wolfram.com/GraphNeighborhood.html)

Here are a few other references: 
- http://mathworld.wolfram.com/GraphNeighborhood.html
- https://en.wikipedia.org/wiki/Neighbourhood_(graph_theory)
- https://en.wikipedia.org/wiki/Glossary_of_graph_theory_terms

**Comment by jayqi** [comment]
@bburns632  Should we ... dare I say it ... consider renaming them again? (😂) I think _not_ including the node in the count is more useful. That way orphan nodes will have both in and out counts of 0. 

What if we called them: `numOutConnected`, `numInConnected`? For number of connected nodes?

**Comment by bburns632** [comment]
This sounds like a taxes question: do you claim yourself as a dependent?  😄 

How about: 
`numDependencies` (things this thing uses, package dependencies, inSubgraph) and 
`numConsumers` (things that use this thing's code, reverse dependencies, outSubgraph)
?  

Let's riff.  I think we can come up with better than those two.  In both of the above, their proposed value is (subgraph number of nodes - 1).

**Comment by jayqi** [comment]
@bburns632 and I just chatted IRL and came up with:
- `recursiveDeps`
- `recursiveRevDeps`
