### ISSUE TITLE
Travis badge should have the travis logo

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet#221]
Now that we have appveyor testing set up (thanks to #220 ), this should be updated:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/7608904/56088951-62d48400-5e50-11e9-9407-133eaa0412aa.png">

We would be grateful if someone would add the Travis logo to the README badge for Travis CI status, similar to https://github.com/dmlc/xgboost/pull/4344/files

**Comment by bburns632** [comment]
That link is broken @jameslamb

**Comment by jameslamb** [comment]
@mcguinlu I'm surprised that GitHub didn't automatically close this when I merged your PR. I guess you have to put `(fixes #221)` in a commit or the PR name? Maybe they don't read from the description. TIL!

Thanks again, hope you'll come back and contribute more on `pkgnet`!

**Comment by mcguinlu** [comment]
@jameslamb I think it is because I had put "Fixes Issue #221" rather than "Fixes #221" in the body of my PR - I reckon including "Issue" prevents it from working. Good to know for future use! 

And yes, definitely will keep an eye out for more issues I could help with - looks like a really interesting project!
