### ISSUE TITLE
function graph flipping

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#41]
A graph is plotted twice from the same package reporter object, and the second plot is flipped compared to the first plot.  The color field is changed between plots, one discrete and the other continuous, but I'm not sure if that's the cause.  The edges are not reversed.   

Both graphs should have the same node arrangement, just different colors. 

**Example:**
```
 b <- PackageFunctionReporter$new()
  b$set_package('baseballstats'
 , packagePath = system.file('baseballstats',package="pkgnet")
 )
  b$calculate_metrics()
  b$get_raw_data()
  b$set_plot_node_color_scheme(field = "coverageRatio"
                               , pallete = c("red", "green")
  )
 
# First Plot
  expect_output(object = plotObj <- b$plot_network()
                , regexp = "Done creating plot"
                , info = "Plot with continuous coloring has issues")
  
  b$set_plot_node_color_scheme(field = "filename"
                               , pallete = RColorBrewer::brewer.pal(9,"Set1")
  )
  
# Second Plot
  expect_output(object = plotObj <- b$plot_network()
                , regexp = "Done creating plot"
                , info = "Plot with continuous coloring has issues")
  ```

**First Plot:** 
![image](https://user-images.githubusercontent.com/24531403/34391871-1d524180-eb0e-11e7-8740-42fa90cc0266.png)

**Second Plot:** 
![image](https://user-images.githubusercontent.com/24531403/34391882-2faf7424-eb0e-11e7-9f70-708801cc469e.png)

**Comment by jayqi** [comment]
I think #46 fixes this bug. I encountered something like this while I was testing my changes. It happened when you call `set_graph_layout()` twice. (Which happened in your case, because you call `plot_network()` twice and `plot_network()` would always call `set_graph_layout()`. At the end of `set_graph_layout()`, it would merge the new node DT that has `level` and `horizontal` columns with the existing node DT. If the existing node DT already had those two columns, then they'd get renamed to `x.level`, `y.level`, etc. Then the plotting wouldn't find the columns and would plot with no layout (the "flipped" case). 

https://github.com/UptakeOpenSource/pkgnet/blob/05c3997e3ebeaca3d2421d881fcffa00ef791819/R/AbstractGraphReporter.R#L172
